name: Release (prod)

on:
  push:
    branches:
      - 'latest'
      # todo: remove after test
      - 'test/prod/**'

jobs:
  # todo uncomment
  # tests-prod:
  #   name: Run all tests
  #   uses: ./.github/workflows/tests.yml
  #   secrets: inherit
  #   with:
  #     all_tests: true

  builds-prod:
    name: Create all builds for release
    uses: ./.github/workflows/build.yml
    # needs: tests-prod
    secrets: inherit
    with:
      environment: 'production'
      target: 'all'

  # virustotal-prod:
  #   name: Virustotal
  #   uses: ./.github/workflows/virustotal.yml
  #   needs: builds-prod
  #   secrets: inherit
  #   with:
  #     skip_report: true

  aws-prod:
    name: Realse to AWS S3
    uses: ./.github/workflows/aws.yml
    if: ${{ always() }}
    # needs: virustotal-prod
    needs: builds-prod
    secrets: inherit

  # todo: uncomment
  # docker-prod:
  #   name: Release docker images
  #   uses: ./.github/workflows/release-docker.yml
  #   needs: aws-prod
  #   secrets: inherit

  # todo: e2e tests for release stage
  # e2e-linux:
  #   uses: ./.github/workflows/build.yml
  #   needs: builds-prod
  #   secrets: inherit
  #   with:
  #     environment: 'staging'
  #     target: 'all'
