name: ‚ùó Release (prod)

on:
  push:
    branches:
      - 'latest'

jobs:
  tests-prod:
    name: Run all tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      group_tests: 'without_e2e'
      short_rte_list: false

  builds-prod:
    name: Create all builds for release
    uses: ./.github/workflows/build.yml
    needs: tests-prod
    secrets: inherit
    with:
      environment: 'production'
      target: 'all'

  e2e-docker-tests:
    name: E2E Docker tests
    needs: builds-prod
    uses: ./.github/workflows/tests-e2e-docker.yml
    secrets: inherit

  e2e-appimage-tests:
    name: E2E AppImage tests
    needs: builds-prod
    uses: ./.github/workflows/tests-e2e-appimage.yml
    secrets: inherit

  virustotal-prod:
    name: Virustotal
    uses: ./.github/workflows/virustotal.yml
    needs: builds-prod
    secrets: inherit
    with:
      skip_report: true

  aws-prod:
    name: Realse to AWS S3
    uses: ./.github/workflows/aws.yml
    needs: virustotal-prod
    secrets: inherit

  docker-prod:
    name: Release docker images
    uses: ./.github/workflows/release-docker.yml
    needs: aws-prod
    secrets: inherit
